"""
Parse captured requests into a payload format for discovered_endpoint.json.
Building request bodies is site-specific: use the site dir's payload_format.py
(e.g. localhost3000/payload_format.py) generated by generate-payload-module.
"""
import json
import re
from typing import Any


def _get_content_type(headers: dict) -> str:
    """Normalize header key to get Content-Type value."""
    for k, v in headers.items():
        if k.lower() == "content-type":
            return (v if isinstance(v, str) else (v[0] if v else "")).strip()
    return ""


def _parse_multipart_boundary(content_type: str) -> str | None:
    """Extract boundary from Content-Type: multipart/form-data; boundary=----..."""
    m = re.search(r"boundary\s*=\s*[\"']?([^\"'\s;]+)", content_type, re.I)
    return m.group(1).strip() if m else None


def _parse_multipart_body(body: str, boundary: str) -> dict[str, str]:
    """Parse multipart/form-data body into a dict of field name -> value."""
    if not body or not boundary:
        return {}
    # Parts are separated by --boundary\r\n (or --boundary-- at end)
    sep = "--" + boundary
    parts = body.split(sep)
    fields: dict[str, str] = {}
    for part in parts:
        part = part.strip()
        if not part or part == "--":
            continue
        # First line(s) are headers; then \r\n\r\n then value
        if "\r\n\r\n" in part:
            header_block, value = part.split("\r\n\r\n", 1)
        elif "\n\n" in part:
            header_block, value = part.split("\n\n", 1)
        else:
            continue
        # Content-Disposition: form-data; name="title"
        name_match = re.search(r'name\s*=\s*["\']([^"\']+)["\']', header_block, re.I)
        if name_match:
            name = name_match.group(1).strip()
            # Value may have trailing \r\n from next part
            value = value.rstrip("\r\n")
            fields[name] = value
    return fields


def parse_payload_from_request(headers: dict, body: Any) -> dict[str, Any]:
    """
    Derive a structured payload_format from captured request headers and body.
    Returns a dict with "encoding", and either "boundary" + "fields" (multipart) or "fields" (JSON).
    """
    content_type = _get_content_type(headers)
    if not content_type:
        return {"encoding": "unknown", "fields": {}}

    # Multipart
    if "multipart/form-data" in content_type.lower():
        boundary = _parse_multipart_boundary(content_type)
        if boundary:
            body_str = body if isinstance(body, str) else (json.dumps(body) if isinstance(body, dict) else "")
            fields = _parse_multipart_body(body_str, boundary)
            return {"encoding": "multipart/form-data", "boundary": boundary, "fields": fields}
        return {"encoding": "multipart/form-data", "fields": {}}

    # JSON
    if "application/json" in content_type.lower():
        if isinstance(body, dict):
            return {"encoding": "application/json", "fields": dict(body)}
        if isinstance(body, str):
            try:
                return {"encoding": "application/json", "fields": json.loads(body)}
            except json.JSONDecodeError:
                pass
        return {"encoding": "application/json", "fields": {}}

    return {"encoding": "unknown", "fields": {}}
