"""
Site-specific payload format (generated by Gemini). Self-contained: builds request
bodies for this site only. Varies per site; do not depend on the shared payload_format.
Handles both flat string fields and structured fields (arrays/objects) via JSON coercion.
"""
import json
import copy
from pathlib import Path
from typing import Any

# payload_key -> form field name (from Gemini analysis)
PAYLOAD_KEY_TO_FIELD = {
  "userMessage": "messages[0].content",
  "prompt": "messages[-1].content",
  "title": "title"
}

PROMPT_FIELD = "messages[-1].content"

# Load strategy-specific formats from discovered_endpoint.json (zero/few/multi-shot)
_here = Path(__file__).resolve().parent
_DISCOVERED_FILE = _here / "discovered_endpoint.json"
STRATEGIES = {}
if _DISCOVERED_FILE.exists():
    try:
        _data = json.loads(_DISCOVERED_FILE.read_text())
        STRATEGIES = _data.get("strategies") or {}
    except Exception:
        pass



def _coerce_value(v: Any) -> Any:
    """If v is a JSON string (array/object), return parsed value so body has correct types."""
    if isinstance(v, str):
        s = v.strip()
        if (s.startswith("[") or s.startswith("{")) and len(s) > 1:
            try:
                return json.loads(s)
            except json.JSONDecodeError:
                pass
    return v


def _build_multipart(boundary: str, fields: dict[str, str]) -> str:
    lines = []
    for name, value in fields.items():
        lines.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"{name}\"\r\n\r\n{value}\r\n")
    lines.append(f"--{boundary}--\r\n")
    return "".join(lines)


def build_body(payload_format: dict[str, Any], overrides: dict[str, Any] | None = None, strategy: str = "zero_shot") -> tuple[str, str]:
    """Merge overrides via PAYLOAD_KEY_TO_FIELD and build body. strategy selects zero_shot/few_shot/multi_shot format when present."""

    if strategy in STRATEGIES and STRATEGIES[strategy].get("payload_format"):
        payload_format = copy.deepcopy(STRATEGIES[strategy]["payload_format"])

    overrides = overrides or {}
    field_overrides = {}
    for k, v in overrides.items():
        api_key = PAYLOAD_KEY_TO_FIELD.get(k, k)
        field_overrides[api_key] = _coerce_value(v)
    encoding = payload_format.get("encoding", "unknown")
    fields = dict(payload_format.get("fields", {}))
    fields.update(field_overrides)
    if encoding == "multipart/form-data":
        boundary = payload_format.get("boundary", "----formboundary")
        str_fields = {k: v if isinstance(v, str) else json.dumps(v) for k, v in fields.items()}
        body = _build_multipart(boundary, str_fields)
        return body, f"multipart/form-data; boundary={boundary}"
    if encoding == "application/json":
        return json.dumps(fields), "application/json"
    return json.dumps(fields), "application/json"
