"""
Site-specific payload format (generated by Gemini). Self-contained: builds request
bodies for this site only. Varies per site; do not depend on the shared payload_format.
Handles both flat string fields and structured fields (arrays/objects) via JSON coercion.
"""
import json
from typing import Any

# payload_key -> form field name (from Gemini analysis)
PAYLOAD_KEY_TO_FIELD = {
  "messages": "messages",
  "title": "title"
}


def _coerce_value(v: Any) -> Any:
    """If v is a JSON string (array/object), return parsed value so body has correct types."""
    if isinstance(v, str):
        s = v.strip()
        if (s.startswith("[") or s.startswith("{")) and len(s) > 1:
            try:
                return json.loads(s)
            except json.JSONDecodeError:
                pass
    return v


def _build_multipart(boundary: str, fields: dict[str, str]) -> str:
    lines = []
    for name, value in fields.items():
        lines.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"{name}\"\r\n\r\n{value}\r\n")
    lines.append(f"--{boundary}--\r\n")
    return "".join(lines)


def build_body(payload_format: dict[str, Any], overrides: dict[str, Any] | None = None) -> tuple[str, str]:
    """Merge overrides via PAYLOAD_KEY_TO_FIELD and build body for this site."""
    overrides = overrides or {}
    field_overrides = {}
    for k, v in overrides.items():
        api_key = PAYLOAD_KEY_TO_FIELD.get(k, k)
        field_overrides[api_key] = _coerce_value(v)
    encoding = payload_format.get("encoding", "unknown")
    fields = dict(payload_format.get("fields", {}))
    fields.update(field_overrides)

    if encoding == "multipart/form-data":
        boundary = payload_format.get("boundary", "----formboundary")
        # Multipart requires string values
        str_fields = {k: v if isinstance(v, str) else json.dumps(v) for k, v in fields.items()}
        body = _build_multipart(boundary, str_fields)
        return body, f"multipart/form-data; boundary={boundary}"
    if encoding == "application/json":
        return json.dumps(fields), "application/json"
    return json.dumps(fields), "application/json"
