"""
Site-specific send_payloads: uses this site's payload_format (generated by Gemini).
Package name from parent dir; payload_format loaded by path so we get this dir's build_body.
"""
import asyncio
import importlib
import importlib.util
import json
import sys
from datetime import datetime
from pathlib import Path

from playwright.async_api import async_playwright

_here = Path(__file__).resolve().parent
# Layout: package_dir / sitename / component / send_payloads.py -> package is 2 levels up
_pkg_dir = _here.parent.parent
_pkg = _pkg_dir.name.replace("-", "_")
if str(_pkg_dir.parent) not in sys.path:
    sys.path.insert(0, str(_pkg_dir.parent))

auth_module = importlib.import_module(f"{_pkg}.auth")
_config_mod = importlib.import_module(f"{_pkg}.config")
AUTH_STATE_FILE = _config_mod.AUTH_STATE_FILE
CSRF_TOKEN_FILE = _config_mod.CSRF_TOKEN_FILE
DISCOVERED_ENDPOINT_FILE = _config_mod.DISCOVERED_ENDPOINT_FILE
PAYLOADS_FILE = _config_mod.PAYLOADS_FILE

# Load this dir's payload_format by path (not the package's parsing-only module)
_pf_spec = importlib.util.spec_from_file_location("site_payload_format", _here / "payload_format.py")
payload_format_module = importlib.util.module_from_spec(_pf_spec)
_pf_spec.loader.exec_module(payload_format_module)


def _load_csrf() -> str:
    if not CSRF_TOKEN_FILE.exists():
        return ""
    try:
        data = json.loads(CSRF_TOKEN_FILE.read_text())
        return data.get("csrf_token", "")
    except (json.JSONDecodeError, OSError):
        return ""


async def send_payloads() -> None:
    if not DISCOVERED_ENDPOINT_FILE.exists():
        print(f"[-] No discovered endpoint at {DISCOVERED_ENDPOINT_FILE}. Run 'discover' first.")
        return
    if not PAYLOADS_FILE.exists():
        print(f"[-] No payloads file at {PAYLOADS_FILE}. Create one with a 'payloads' array of {{'title', 'text'}}.")
        return
    if not AUTH_STATE_FILE.exists():
        print(f"[-] No session at {AUTH_STATE_FILE}. Run 'login' first.")
        return

    discovered = json.loads(DISCOVERED_ENDPOINT_FILE.read_text())
    payload_format = discovered.get("payload_format")
    if not payload_format or not payload_format.get("fields"):
        print("[-] No payload_format in discovered endpoint. Run 'discover' then 'generate-payload-module'.")
        return

    payloads_data = json.loads(PAYLOADS_FILE.read_text())
    payloads = payloads_data.get("payloads", payloads_data) if isinstance(payloads_data, dict) else payloads_data
    if not payloads:
        print("[-] No payloads in file (expect 'payloads' array).")
        return

    if not await auth_module.ensure_session_fresh():
        print("[-] Session refresh failed. Run 'login' or 'refresh' and try again.")
        return

    url = discovered["url"]
    headers = dict(discovered.get("headers", {}))
    headers.pop("content-length", None)
    headers.pop("host", None)
    headers.pop("accept-encoding", None)
    csrf = _load_csrf()
    if csrf:
        headers["X-CSRF-Token"] = csrf
        headers["X-XSRF-TOKEN"] = csrf

    results = []
    async with async_playwright() as p:
        api_context = await p.request.new_context(storage_state=str(AUTH_STATE_FILE))
        try:
            for i, p_item in enumerate(payloads):
                overrides = {}
                for k, v in p_item.items():
                    if v is None:
                        continue
                    if isinstance(v, str):
                        overrides[k] = v
                    elif isinstance(v, (dict, list)):
                        overrides[k] = json.dumps(v)
                    else:
                        overrides[k] = str(v)
                label = p_item.get("title") or p_item.get("companyName") or (list(p_item.values())[0] if p_item else f"Payload {i+1}")
                if isinstance(label, (dict, list)):
                    label = str(label)
                body, content_type = payload_format_module.build_body(payload_format, overrides)
                req_headers = {**headers, "Content-Type": content_type}
                try:
                    response = await api_context.post(url, headers=req_headers, data=body)
                    resp_text = await response.text()
                    results.append({"title": label, "status": response.status, "ok": response.ok, "response": resp_text})
                    if not response.ok:
                        print(f"  [{response.status}] {label}" + (f" — {resp_text}" if resp_text else ""))
                    else:
                        print(f"  [{response.status}] {label}")
                        print(f"    response: {resp_text}")
                except Exception as e:
                    results.append({"title": label, "status": None, "ok": False, "error": str(e), "response": None})
                    print(f"  [error] {label} — {e}")
        finally:
            await api_context.dispose()

    ok_count = sum(1 for r in results if r.get("ok"))
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    log_path = PAYLOADS_FILE.parent / f"{timestamp}_log.json"
    log_path.write_text(json.dumps({"timestamp": timestamp, "results": results}, indent=2), encoding="utf-8")
    print(f"[+] Log: {log_path}")
    print(f"\n[*] Sent {len(results)} payloads, {ok_count} OK.")
